### ISSUE TITLE
netX TLS 1.2 server mutual auth do not respond after a first client connection without client certificate

### ISSUE THREAD

**Issue by EdouardMALOT** [eclipse-threadx/netxduo#57]
If netX TLS is set as server mutual auth and the client try to connect in TLS 1.2 without certificate the alert "Bad certificate" is sent twice, connection isn't closed and server do not listen anymore : 
- 192.168.2.1 : is the PC (client)
- 192.168.2.2 : is the netX server (server)

<img width="1444" alt="Pasted Graphic 1" src="https://user-images.githubusercontent.com/11795982/139070894-4ac6f6af-e978-4224-873b-006937a1d2ff.png">

My workaround is to comment "send alert process" in _nx_secure_tls_server_handshake(). (send alert is done later, at higher level) : 
<img width="1015" alt="Pasted Graphic 3" src="https://user-images.githubusercontent.com/11795982/139074634-3a8089e6-aca3-4e77-9158-8c3c8ad53cb5.png">

With this correction, the alert message is sent once (Packet 18) and the connection is closed correctly:
<img width="1436" alt="Pasted Graphic 4" src="https://user-images.githubusercontent.com/11795982/139075048-af9308bc-24cd-4b2f-9cc3-676ba38a95bc.png">
 
Note : this issue does'n t happen in TLS 1.3

**Comment by umut04** [comment]
Hi,

How can I disable secure client-initiated renegotiation vulnerable (not ok) in an application running IIS?

![image](https://user-images.githubusercontent.com/92626486/159229514-d90e33f6-aa34-45c1-8835-060fff17b215.png)

**Comment by umut04** [comment]
@DoudFPV

**Comment by DoudFPV** [comment]
I don't understand where comes from this screen shot, can you give details ?

**Comment by umut04** [comment]
In a security scan, it is requested to disable SSL/TLS renegotiation for an application that is open to the outside world and running on windows IIS.

**Comment by DoudFPV** [comment]
interesting, can you tell me which script you use with which parameters ?

**Comment by hwmaier** [comment]
@umut04 Setting `NX_SECURE_TLS_DISABLE_CLIENT_INITIATED_RENEGOTIATION` in nx_user.h disables it. This feature has been added in version 6.1.9. 

Refer to this conversation  https://github.com/azure-rtos/netxduo/issues/49 for more details.

@DoudFPV The script is [ssltest.sh](https://testssl.sh/)
